name: ServerPassword
version: '${version}'
main: es.mrdino.serverpassword.ServerPassPlugin
api-version: '${apiVersion}'
loadbefore:
  - PerPlayerProfiles

commands:
  serverpass:
    description: Enter the server password
    usage: /serverpass <password>
  spass:
    description: Admin commands for ServerPassword
    usage: /spass help

permissions:
  serverpassword.admin:
    default: op
